force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <description>HKA 30.12.2020
Invoice object used for invoicing Nya-soft Customer</description>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{00000}</displayFormat>
        <label>Invoice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <formula>Days__c  *  Unit_price__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Bank_Account__c.field-meta.xml
<CustomField>
    <fullName>Bank_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Bank Account</label>
    <referenceTo>Bank_Account__c</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Bill_To__c.field-meta.xml
<CustomField>
    <fullName>Bill_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Related to Account</description>
    <label>Bill To</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <description>Invoicing Date</description>
    <label>Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Days__c.field-meta.xml
<CustomField>
    <fullName>Days__c</fullName>
    <description>Number of days</description>
    <label>Days</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/TAX_RATE__c.field-meta.xml
<CustomField>
    <fullName>TAX_RATE__c</fullName>
    <label>TAX RATE</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/TOTAL__c.field-meta.xml
<CustomField>
    <fullName>TOTAL__c</fullName>
    <formula>Amount__c + ( Amount__c *  TAX_RATE__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>TOTAL</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Unit_price__c.field-meta.xml
<CustomField>
    <fullName>Unit_price__c</fullName>
    <label>Unit price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/CINV_InvoiceController.cls
public with sharing class CINV_InvoiceController {
    public Invoice__c invoice {get;set;}
    public Invoice__c currentnvoice {get;set;}
    public CINV_InvoiceController(ApexPages.StandardController controller) {
        invoice=(Invoice__c)controller.getRecord();
        invoice=[select id,name,date__c,Bill_To__r.name,Bill_To__r.BillingStreet,Bill_To__r.BillingCity
        ,Bill_To__r.BillingCountry,Bill_To__r.BillingPostalCode,Bill_To__r.Phone,days__c,Bill_To__r.Id
        ,AMOUNT__c,Unit_price__c,description__c
        ,tax_rate__c,tax__c,total__c,Bank_Account__r.name
        
         from Invoice__c where id=:invoice.id];

         currentnvoice=[select id,name
        
         from Invoice__c where id=:invoice.id];
         


    }

          //HKA 09.12.2020 redirect and save the PDf in file Object [Bon de livraison]
          Public PageReference SaveInvoice(){
            PageReference retURL;
    
         
    
                if( ApexPages.currentPage().getParameters().containsKey('uploadMode')) return null;
    
                PageReference PDFExportedPage = new PageReference('/apex/CINV_InvoicePage1?id='+ ApexPages.currentPage().getParameters().get('id')+'&uploadMode=true');
        
                Blob pdfContent = blob.valueOf('Unit.Test');
                
                pdfContent = PDFExportedPage.getContentAsPDF();
                
        
                ContentVersion ContVerFile = new ContentVersion();
                ContVerFile.VersionData = pdfContent;
                ContVerFile.Title =currentnvoice.Name; 
                ContVerFile.ContentLocation= 's';
                ContVerFile.PathOnClient=currentnvoice+'.pdf';
        
                insert ContVerFile;
        
                Id PDFcontentDoc = [SELECT ContentDocumentId FROM ContentVersion WHERE Id =:ContVerFile.Id].ContentDocumentId;
                ContentDocumentLink InvoicePDF = new ContentDocumentLink();
                InvoicePDF.ContentDocumentId = PDFcontentDoc;
                InvoicePDF.LinkedEntityId = ApexPages.currentPage().getParameters().get('id');
                InvoicePDF.ShareType = 'I';
                InvoicePDF.Visibility = 'AllUsers';
        
                insert InvoicePDF;
           
    
    
            return retURL;
        }
}